# Generated by Django 5.2.1 on 2025-05-20 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_chamado', models.CharField(choices=[('ERRO', 'Erro'), ('MELHORIA', 'Melhoria'), ('DÚVIDA', 'Dúvida')], max_length=20)),
                ('descricao', models.TextField()),
                ('modulo', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao_horas', models.DateTimeField(blank=True, null=True)),
                ('horas_estimadas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('horas_aprovadas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_alterados', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='projetos.projeto')),
                ('recurso_alocado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_alocados', to=settings.AUTH_USER_MODEL)),
                ('user_abertura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
