# Generated by Django 5.2.1 on 2025-05-20 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('horas_alocacao_gerente', models.DecimalField(decimal_places=2, help_text='Horas alocadas do gerente', max_digits=6)),
                ('data_inicio_contrato', models.DateField()),
                ('data_fim_contrato', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='clientes.cliente')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
